### ISSUE TITLE
Nice repo

### ISSUE THREAD

**Issue by Patrikgrinsvall** [rtcoder/deployer#1]
I found this by coincidence and cloned and tested it. If the final few issues are resolved this is something really needed imo.

Did you give up on development? 
(I'm going to build something similar for a client soon, but question is if i should continue where you left off or start from scratch or find another to build upon)

**Comment by rtcoder** [comment]
I'm planning to continue development but for now I'm in hospital and I cannot do anything with it. You can continue if you want. I would be glad 🙂
